# .NET Desktop

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: 'winPEAS/winPEASexe/*.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(New-Object Net.WebClient).DownloadFile("https://github.com/3lpsy/s3upload/releases/download/0.0.1/s3upload-windows-amd64", "./s3upload.exe")'
    failOnStderr: true
    workingDirectory: '$(Build.SourcesDirectory)'