# .NET Desktop

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: 'winPEAS/winPEASexe/*.sln'
    msbuildArchitecture: 'x64'
    platform: 'x64'
    configuration: 'release'
    clean: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(New-Object Net.WebClient).DownloadFile("https://github.com/3lpsy/s3upload/releases/download/0.0.1/s3upload-windows-amd64", "$(Build.SourcesDirectory)/s3upload.exe")'
    failOnStderr: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$(Build.SourcesDirectory)/s3upload.exe -source $(Build.SourcesDirectory)/winPEAS/winPEASexe/winPEAS/bin/x64/Release/winPEAS.exe -destination /winPEAS40.exe'
    failOnStderr: true
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_BUCKET: $(AWS_BUCKET)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '((Get-Content -path winPEAS/winPEASexe/winPEAS/winPEAS.csproj -Raw) -replace "v4.0","v3.5") | Set-Content -Path winPEAS/winPEASexe/winPEAS/winPEAS.csproj'
    failOnStderr: true
    workingDirectory: '$(Build.SourcesDirectory)'


- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: 'winPEAS/winPEASexe/*.sln'
    msbuildArchitecture: 'x64'
    platform: 'x64'
    configuration: 'release'
    clean: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$(Build.SourcesDirectory)/s3upload.exe -source $(Build.SourcesDirectory)/winPEAS/winPEASexe/winPEAS/bin/x64/Release/winPEAS.exe -destination /winPEAS35.exe'
    failOnStderr: true
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_BUCKET: $(AWS_BUCKET)